### ISSUE TITLE
MSVC output - assert with precompiled headers

### ISSUE THREAD

**Issue by Jaa-c** [Phyronnaz/UECompilationTimesVisualizer#1]
Hi, I have a Qt project with precompiled headers and for my output, I end up with an assert:

```
    Parsing includes...
Traceback (most recent call last):
  File "main.py", line 278, in <module>
    includes_tree = parse_section(current_file, get_include_name)
  File "main.py", line 226, in parse_section
    count = parse_count()
  File "main.py", line 111, in parse_count
    return parse_int("Count:")
  File "main.py", line 95, in parse_int
    assert string in line, "{} not in {}".format(string, line)
AssertionError: Count: not in cl -c -Yc -Fprelease\Base_pch.pch -Forelease\Base_pch.obj /Bt+ /d2cgsummary /d1reportTime /std:c++17 -DNDEBUG /Fdrelease\Base.vc.pdb -TP ..\..\src\Base\stable.h
```

I've attached the beginning of the log: [sample_log.txt](https://github.com/Phyronnaz/UECompileTimesVisualizer/files/2764386/sample_log.txt)

Thanks for looking into it.

**Comment by Phyronnaz** [comment]
@Jaa-c Added some code to support that log, there will probably still be some error for the full log though

**Comment by Jaa-c** [comment]
Thanks for the quick fix! There are some other issues, I'll try to fix them and will create a pull request. If I can't do it, I'll try to create some small sample log...
